[project]
name = "pico-vllm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cmake>=4.1.2",
    "tqdm>=4.67.1",
    "transformers==4.55.4",
    "xxhash>=3.6.0",
    "torch==2.8.0",
    "intel_extension_for_pytorch==2.8.0",
    "setuptools>=80.9.0",
    "viztracer>=1.1.1",
]


[tool.uv.sources]
torch = [
  { index = "pytorch-cpu" },
]


[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
